services:
  postgres:
    image: postgres:15
    container_name: lms-postgres
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lms_user -d lms"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "8080:8080"

  user:
    build: ./user-service
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lms
      SPRING_DATASOURCE_USERNAME: lms_user
      SPRING_DATASOURCE_PASSWORD: lms_pass
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      gateway:
        condition: service_healthy
  
  course:
    build: ./courses-service
    container_name: courses-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lms
      SPRING_DATASOURCE_USERNAME: lms_user
      SPRING_DATASOURCE_PASSWORD: lms_pass
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      gateway:
        condition: service_healthy
      user:
        condition: service_healthy

  assignment:
    build: ./assignments-service
    container_name: assignments-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lms
      SPRING_DATASOURCE_USERNAME: lms_user
      SPRING_DATASOURCE_PASSWORD: lms_pass
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
      gateway:
        condition: service_healthy
      user:
        condition: service_healthy
      course:
        condition: service_healthy
  
  content:
    build: ./content-service
    container_name: content-service
    # environment:
      # SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lms
      # SPRING_DATASOURCE_USERNAME: lms_user
      # SPRING_DATASOURCE_PASSWORD: lms_pass
    ports:
      - "8084:8084"
    depends_on:
      assignment:
        condition: service_healthy
      gateway:
        condition: service_healthy
      user:
        condition: service_healthy
      course:
        condition: service_healthy

volumes:
  postgres_data:

